{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "durable-engine.fullname" . }}
  labels:
    {{- include "durable-engine.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
