apiVersion: v1
kind: Service
metadata:
  name: {{ include "durable-engine.fullname" . }}
  labels:
    {{- include "durable-engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ingestPort }}
      targetPort: ingest
      protocol: TCP
      name: ingest
    - port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "durable-engine.selectorLabels" . | nindent 4 }}
