apiVersion: apps/v1
kind: Deployment
metadata:
  name: durable-engine
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: durable-engine
          resources:
            requests:
              cpu: "1"
              memory: 512Mi
            limits:
              cpu: "4"
              memory: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - durable-engine
                topologyKey: kubernetes.io/hostname
