apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prod-durable-engine
  labels:
    app.kubernetes.io/name: durable-engine
spec:
  minAvailable: "50%"
  selector:
    matchLabels:
      app.kubernetes.io/name: durable-engine
