apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: durable-engine

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: durable-engine
