apiVersion: apps/v1
kind: Deployment
metadata:
  name: durable-engine  # container name to identify the container in the pod.
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: durable-engine
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 512Mi
