apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: durable-engine-staging

namePrefix: staging-

resources:
  - ../../base
  - hpa.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: durable-engine
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: durable-engine-config

images:
  - name: durable-engine
    newName: ghcr.io/adityap-cruv/durable-engine
    newTag: staging
